//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pso.cdd.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cab_ts
    {
        public int ts_id { get; set; }
        public int id_usu { get; set; }
        public int id_emp { get; set; }
        public int id_cat { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha { get; set; }
		[Display(Name = "Horas")]
        public int horas { get; set; }
        public int descuento { get; set; }
        [Display(Name = "Glosa")]
        [MaxLength(250)]
        public string descr_esp { get; set; }
        [Display(Name = "Glosa Inglés")]
        public string descr_ing { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fecha_mod { get; set; }
        [Display(Name = "Usuario Modificador")]
        public string usuario_mod { get; set; }
        public string estado { get; set; }
        public int id_tser { get; set; }
        public int grupo { get; set; }
        public string dueño_grupo { get; set; }
        [Display(Name = "Tarifa")]
        public decimal valor_hh { get; set; }
        public int horas_comerciales { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual tipos_servicios tipos_servicios { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
