//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pso.cdd.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class categorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categorias()
        {
            this.cab_ts = new HashSet<cab_ts>();
            this.emp_car_tsrv = new HashSet<emp_car_tsrv>();
            this.unidades1 = new HashSet<unidades>();
        }

        public int id_cat { get; set; }
        [Display(Name = "Categoria")]
        public string nom_cat { get; set; }
        [Display(Name = "Fecha Modificación")]
        public System.DateTime fecha_mod { get; set; }
        [Display(Name = "Usuario Modificador")]
        public string usuario_mod { get; set; }
        public bool estado { get; set; }
        public int id_unidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cab_ts> cab_ts { get; set; }
        public virtual unidades unidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_car_tsrv> emp_car_tsrv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unidades> unidades1 { get; set; }
    }
}
