//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pso.cdd.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_car_tsrv
    {
        public int id_emp { get; set; }
        public int id_cat { get; set; }
        public int id_tser { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual tipos_servicios tipos_servicios { get; set; }
    }
}
