//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pso.cdd.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class periodos
    {
        public int id_periodo { get; set; }
        public int id_tser { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha Inicio")]
        public System.DateTime fecha_ini { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha Fin")]
        public System.DateTime fecha_fin { get; set; }
        public Nullable<bool> estado { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fecha_mod { get; set; }
        [Display(Name = "Usuario Modificador")]
        public string usuario_mod { get; set; }

        [Display(Name = "Tipo Servicio")]
        public virtual tipos_servicios tipos_servicios { get; set; }
    }
}
