//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pso.cdd.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tipos_servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipos_servicios()
        {
            this.cab_ts = new HashSet<cab_ts>();
            this.periodos = new HashSet<periodos>();
            this.emp_car_tsrv = new HashSet<emp_car_tsrv>();
        }
    
        public int id_tser { get; set; }
        [Display(Name = "Tipo servicio")]
        public string nom_tser { get; set; }
        [Display(Name = "Fecha Modificación")]
        public Nullable<System.DateTime> fecha_mod { get; set; }
        [Display(Name = "Usuario Modificador")]
        public string usuario_mod { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cab_ts> cab_ts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<periodos> periodos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_car_tsrv> emp_car_tsrv { get; set; }
    }
}
