//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pso.cdd.model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class valor_hh
    {
        public int id_valor { get; set; }
        public int id_emp { get; set; }
        public int id_unidad { get; set; }
        public int id_cargo { get; set; }
        public decimal valor { get; set; }
        public Nullable<System.DateTime> fecha_mod { get; set; }
        [Display(Name = "Usuario Modificador")]
        public string usuario_mod { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual cargos cargos { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual unidades unidades { get; set; }
    }
}
